apps/users/urls.py
from django.urls import include, path
from apps.users.views import (
    DashboardView, ProfileUpdateView, UserListView, UserUpdateView,
    UserCreateView, UserSetPasswordView
)


app_name = 'users'

urlpatterns = [
    path('', UserListView.as_view(), name='user_list'),
    path('new/', UserCreateView.as_view(), name='new_user'),
    path('<pk>/set-password/', UserSetPasswordView.as_view(), name='set_password'),
    path('dashboard/', DashboardView.as_view(), name='dashboard'),
    path('profile/', DashboardView.as_view(), name='profile'),
    path('profile/update/', ProfileUpdateView.as_view(), name='update_profile'),
    path('<pk>/update/', UserUpdateView.as_view(), name='update_user'),
]

holofin/urls.py
from django.contrib import admin
from django.shortcuts import redirect
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


def home(request):
    return redirect('users:dashboard')
    

urlpatterns = [
    path('', home),
    path('d/admin/', admin.site.urls),
    path('core/', include('apps.core.urls')),
    path('users/', include('apps.users.urls')),
    path('auth/', include('apps.users.auth_urls')),
    path('institution/', include('apps.institution.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/users/models.py
from time import perf_counter
from django.templatetags.static import static
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.urls import reverse
from apps.core.models import AbstractModel
from apps.institution.models import Institution
from .validators import MobileValidator, NationalCodeValidator
from .managers import CustomUserManager



class User(AbstractUser, AbstractModel):
    """Custom User model"""
    class DeactivateReasons(models.IntegerChoices):
        UNKNOWN = 0, 'نامشخص'
        BY_ADMIN = 1, 'غیر فعال توسط مدیر'
        VERIFY_MOBILE = 2, 'عدم تایید موبایل'
        VERIFY_EMAIL = 3, 'عدم تایید ایمیل'
    
    class Roles(models.IntegerChoices):
        ADMIN = 0, 'مدیر'
        USER = 1, 'کاربر'

    mobile = models.CharField('موبایل', max_length=11, unique=True,
                              help_text='موبایل باید به فرمت 09123456789 وارد شود',
                              validators=[MobileValidator()],
                              error_messages={
                                  'unique': 'این شماره موبایل از قبل در سامانه ثبت شده است',
                                },
                            )
    password = models.CharField('گذرواژه', max_length=128, null=True, blank=True)
    first_name = models.CharField(verbose_name='نام', max_length=150, blank=True)
    last_name = models.CharField(verbose_name='نام خانوادگی', max_length=150, blank=True)
    national_code = models.CharField(max_length=10, verbose_name='کد ملی',
                                     validators=[NationalCodeValidator()],
                                     null=True, blank=True, unique=True)
    deactivate_reason = models.PositiveSmallIntegerField(choices=DeactivateReasons.choices,
                                                         default=DeactivateReasons.UNKNOWN,
                                                         verbose_name='غیرفعال به دلیل')
    email = models.EmailField(unique=True, null=True, blank=True, verbose_name='ایمیل')
    address = models.TextField(verbose_name='آدرس', null=True, blank=True)
    birth_date = models.DateField(verbose_name='تاریخ تولد', null=True, blank=True)
    role = models.IntegerField(choices=Roles.choices, default=Roles.USER, verbose_name='نقش')
    phone_number = models.CharField(max_length=15, verbose_name='شماره تلفن ثابت', null=True, blank=True)
    notes = models.TextField(verbose_name='یادداشت', null=True, blank=True)
    avatar = models.ImageField(verbose_name='تصویر پروفایل', upload_to='users/avatars', null=True, blank=True)
    deposit_quantity = models.PositiveIntegerField(verbose_name='تعداد سهم', default=1)
    institution = models.ForeignKey(Institution, on_delete=models.PROTECT, null=True, related_name='users')
    objects = CustomUserManager()

    REQUIRED_FIELDS = ["mobile", ]

    class Meta:
        verbose_name = 'کاربر'
        verbose_name_plural = 'کاربر'
        ordering = ('-id',)

    def __str__(self):
        role = self.get_role_display()
        return f'{self.display_name} ({role})'

    def get_absolute_url(self):
        return reverse('users:user_details', kwargs={'pk': self.pk})

    def save(self, *args, **kwargs):
        if self.email == '':
            self.email = None
        if self.role == self.Roles.ADMIN:
            self.is_staff = True
            self.is_superuser = True
        super().save(*args, **kwargs)

    @property
    def display_name(self) -> str:
        return (
            self.first_name + ' ' + self.last_name
            if self.first_name and self.last_name
            else self.mobile
        )

    @property
    def avatar_url(self) -> str:
        if self.avatar:
            return self.avatar.url
        f = static('account/profile.png')
        return f

    def deactivate(self, reason: DeactivateReasons):
        """Deactivate user by reason

        DO NOT explicitly set users is_active field without saving the reason why it is deactivated
        """
        self.deactivate_reason = reason
        self.is_active = False
        self.save()

    def activate(self):
        """Activate user

        Will change user's deactivate reason to UNKNOWN
        """
        self.deactivate_reason = self.DeactivateReasons.UNKNOWN
        self.is_active = True
        self.save()

    @property
    def is_admin(self):
        return self.role == self.Roles.ADMIN

    @property
    def is_simple_user(self):
        return self.role == self.Roles.USER

apps/users/forms.py
from secrets import choice
from django import forms
from django_filters import FilterSet
from django.contrib.auth import get_user_model
from apps.core import utils
User = get_user_model()


class UserForm(forms.ModelForm):
    password_confirm = forms.CharField(
        label='تکرار رمز عبور',
        widget=forms.PasswordInput(attrs={'class': 'form-control'}),
    )
    password= forms.CharField(
        label='رمز عبور',
        widget=forms.PasswordInput(attrs={'class': 'form-control'}),
    )

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'mobile', 'role', 'avatar', 'password', 'password_confirm']

    def clean_mobile(self):
        mobile = self.cleaned_data['mobile']
        mobile = utils.persian_digits_to_english(mobile)
        return mobile

    def clean_password(self):
        password = self.cleaned_data.get('password')
        if len(password) < 8:
            raise forms.ValidationError('رمز عبور باید حداقل 8 کاراکتر باشد')
        if password.isdigit():
            raise forms.ValidationError('رمز عبور نمیتواند تنها شامل عدد باشد')
        return password

    def clean_password_confirm(self):
        password = self.cleaned_data.get('password')
        password_confirm = self.cleaned_data.get('password_confirm')
        if not password:
            return password_confirm
        if password != password_confirm:
            raise forms.ValidationError('رمز عبور و تکرار آن باید یکسان باشد')
        return password_confirm

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['first_name'].required = True
        self.fields['last_name'].required = True

        
class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'mobile', 'role', 'avatar']

    def clean_mobile(self):
        mobile = self.cleaned_data['mobile']
        mobile = utils.persian_digits_to_english(mobile)
        return mobile

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['role'].widget.choices = UserForm.remove_patient_from_roles(User.Roles.choices)
        self.fields['first_name'].required = True
        self.fields['last_name'].required = True
 
        
class UserSetPasswordForm(forms.ModelForm):
    password_confirm = forms.CharField(
        label='تکرار رمز عبور',
        widget=forms.PasswordInput(attrs={'class': 'form-control'}),
    )
    password= forms.CharField(
        label='رمز عبور',
        widget=forms.PasswordInput(attrs={'class': 'form-control'}),
    )


    class Meta:
        model = User
        fields = ['password', 'password_confirm']

    def clean_password(self):
        password = self.cleaned_data.get('password')
        if len(password) < 8:
            raise forms.ValidationError('رمز عبور باید حداقل 8 کاراکتر باشد')
        if password.isdigit():
            raise forms.ValidationError('رمز عبور نمیتواند تنها شامل عدد باشد')
        return password

    def clean_password_confirm(self):
        password = self.cleaned_data.get('password')
        password_confirm = self.cleaned_data.get('password_confirm')
        if not password:
            return password_confirm
        if password != password_confirm:
            raise forms.ValidationError('رمز عبور و تکرار آن باید یکسان باشد')
        return password_confirm


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'national_code',
                  'email', 'address', 'avatar', 'deposit_quantity')
         

apps/users/views.py
from django.urls import reverse_lazy
from django.shortcuts import get_object_or_404, redirect, render
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils.translation import gettext_lazy as _
from django.views.generic import View, ListView, CreateView, UpdateView, TemplateView, FormView
from jalali_date import date2jalali, datetime2jalali
from apps.core.permissions import PermissionRequireMixin, Permissions
from apps.core.base import BaseContextMixin, GenericFormView, GenericModelFormView
from apps.core.mixins import CustomFormTemplateMixin, CustomListTemplateMixin
from .forms import UserForm, UserProfileForm, UserUpdateForm, UserSetPasswordForm
User = get_user_model()


class DashboardView(LoginRequiredMixin, BaseContextMixin, View):
    def get(self, request, *args, **kwargs):
        context = self.get_context_data(**kwargs)
        return render(request, 'users/dashboard.html', context)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


class ProfileUpdateView(LoginRequiredMixin, CustomFormTemplateMixin, UpdateView):
    model = User
    form_class = UserProfileForm
    success_url = reverse_lazy('users:dashboard')
    success_message = 'اطلاعات شما با موفقیت بروزرسانی شد.'
    page_title = 'ویرایش پروفایل'

    def get_page_subtitle(self):
        user = self.request.user
        return user.get_full_name()

    def get_object(self, queryset=None):
        return self.request.user

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['extra_scripts'] = ['users/scripts/career_dropdown.js']
        return context

        
class UserListView(CustomListTemplateMixin, PermissionRequireMixin, ListView):
    permissions =  [User.Roles.ADMIN, ]
    page_title = 'لیست کاربران'
    context_object_name = 'users'
    paginate_by = 100
    ordering = '-created_at'
    fields = ['username', 'first_name', 'last_name', 'role',]
    header_buttons = [{'title': 'افزودن کاربر', 'url': reverse_lazy('users:new_user')}]
    action_buttons = [
        {'title': 'ویرایش', 'url_name': 'users:update_user', 'arg_field': 'id',
         'fa-icon': 'fa-edit', 'class': '', 'class_form_field': 'id'},
        {'title': 'تغییر رمز', 'url_name': 'users:set_password', 'arg_field': 'id',
         'fa-icon': 'fa-edit', 'class': 'btn-warning', 'class_form_field': 'id'},
    ]

    def get_queryset(self):
        institution = self.request.user.institution
        return User.objects.filter(institution=institution)

    def get_role(self, obj):
        return obj.get_role_display()

    def get_created_at(self, obj):
        return datetime2jalali(obj.created_at).strftime('%Y/%m/%d %H:%M:%S')

    def get_last_login(self, obj):
        last_login = obj.last_login
        if last_login:
            return datetime2jalali(last_login).strftime('%Y/%m/%d %H:%M:%S')
        return '-'


class UserCreateView(CustomFormTemplateMixin, PermissionRequireMixin, CreateView):
    permissions = [User.Roles.ADMIN]
    model = User
    form_class = UserForm
    page_title = 'افزودن کاربر جدید'
    success_url = reverse_lazy('users:user_list')
    cancel_url = reverse_lazy('users:user_list')
    success_message = ' کاربر جدید با موفقیت ثبت شد.'

    def form_valid(self, form):
        user = form.save(commit=False)
        password = user.password
        user.username = user.mobile
        user.institution = self.request.user.institution
        user.set_password(password)
        user.save()
        return super().form_valid(form)



class UserUpdateView(UserCreateView, UpdateView):
    page_title = 'ویرایش کاربر'
    success_message = 'کاربر با موفقیت ویرایش شد.'
    form_class = UserUpdateForm


class UserSetPasswordView(CustomFormTemplateMixin, PermissionRequireMixin, FormView):
    permissions = [User.Roles.ADMIN]
    model = User
    form_class = UserSetPasswordForm
    success_url = reverse_lazy('users:user_list')
    success_message = 'رمز عبور با موفقیت بروزرسانی شد.'
    page_title = 'تغییر رمز عبور'
    
    def get_page_subtitle(self):
        user = self.get_object()
        return user.get_full_name()

    def get_object(self, queryset=None):
        pk = self.kwargs.get('pk')
        return get_object_or_404(User, pk=pk)
    
    def form_valid(self, form):
        user = self.get_object()
        user.set_password(form.cleaned_data['password'])
        user.save()
        return super().form_valid(form)


class UserDetailView(PermissionRequireMixin ,TemplateView):
    permissions = [User.Roles.ADMIN]
    template_name = 'users/user_detail_view.html'
    context_object_name = 'user'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = get_object_or_404(User, id=kwargs['pk'])
        context["user"] = user
        return context

apps/users/templates/users/dashboard.html
{% extends 'base.html' %}
{% load static jalali_tags %}

{% block extra_head %}
  <script src="{% static 'js/gauge.min.js' %}"></script>
{% endblock extra_head %}

{%block page_content%}
<div class="row" style="display: flex">
  <div class="col-md-8 col-sm-8 col-xs-12 equal-height-parent">
    <div class="x_panel">
      <div class="x_title">
        <h2>
          صفحه پروفایل کاربر
          <small>#{{user.id}}</small>
        </h2>
        <ul class="nav navbar-right panel_toolbox">
          <li>
            <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
          </li>
        </ul>
        <div class="clearfix"></div>
      </div>
      <div class="x_content">
        <div class="col-md-3 col-sm-3 col-xs-12 profile_left">
          <div class="profile_img">
            <div id="crop-avatar">
              <img
                class="img-responsive avatar-view"
                src="{{user.avatar_url}}"
                alt="{{user.display_name}}"
                title="Change the avatar"
              />
            </div>
          </div>
          <h3 class="text-3xl my-4 font-medium">{{user.display_name}}</h3>
          <ul class="list-unstyled user_data">
            <li class="m-top-xs">
              <i class="fa fa-list-alt"></i>
              {{user.national_code|default:'کد ملی تنظیم نشده'}}
            </li>
            <li class="m-top-xs">
              <i class="fa fa-user"></i>
              تعداد سهم:
              {{user.deposit_quantity|default:'0'}}
            </li>
            <li class="m-top-xs">
              <i class="fa fa-envelope"></i>
              {{user.email|default:'آدرس ایمیل تنظیم نشده'}}
            </li>
            <li class="m-top-xs">
              <i class="fa fa-phone"></i>
              {{user.mobile}}
            </li>
          </ul>
          <a class="btn btn-success" href={% url 'users:update_profile' %}
            ><i class="fa fa-edit m-right-xs"></i>&nbsp;ویرایش پروفایل</a
          >
          <br />
        </div>
        <div class="col-md-9 col-sm-9 col-xs-12">
          <div class="" role="tabpanel" data-example-id="togglable-tabs">
            <ul id="myTab" class="nav nav-tabs bar_tabs" role="tablist">
              <li role="presentation" class="active">
                <a
                  href="#tab_content1"
                  id="home-tab"
                  role="tab"
                  data-toggle="tab"
                  aria-expanded="true"
                  >فعالیت اخیر</a
                >
              </li>
              <li role="presentation" class="">
                <a
                  href="#tab_content2"
                  role="tab"
                  id="profile-tab"
                  data-toggle="tab"
                  aria-expanded="false"
                  >درخواست‌های پرداخت نشده</a
                >
              </li>
              <li role="presentation" class="">
                <a
                  href="#tab_content3"
                  role="tab"
                  id="profile-tab2"
                  data-toggle="tab"
                  aria-expanded="false"
                  >پروفایل</a
                >
              </li>
            </ul>
            <div id="myTabContent" class="tab-content">
              <div
                role="tabpanel"
                class="tab-pane fade active in"
                id="tab_content1"
                aria-labelledby="home-tab"
              >
                
              </div>
              <div
                role="tabpanel"
                class="tab-pane fade"
                id="tab_content2"
                aria-labelledby="profile-tab"
              >
                
              </div>
              <div
                role="tabpanel"
                class="tab-pane fade"
                id="tab_content3"
                aria-labelledby="profile-tab"
              >
                <p>
                  
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{%endblock page_content%}

{% block extra_scripts %}
  <script>
    var options = {
      lines:12,
      angle:0, 
      lineWidth:.4, 
      pointer: { 
        length:.75,
        strokeWidth:.042,
        color:"#1D212A"
      },
      limitMax:"false",
      colorStart:"#1ABC9C",
      colorStop:"#1ABC9C",
      strokeColor:"#F0F3F3",
      generateGradient:!0,
      maxValue:80
    }
    var target = document.getElementById('referral_code_gauge');
    var gauge = new Gauge(target).setOptions(options);
    gauge.maxValue = 10;
    gauge.setMinValue(0);
    gauge.animationSpeed = 32;
    gauge.set({{user.total_referred_users}});

    function copyToClipboard(text) {
      navigator.clipboard.writeText(text);
      showInfoMessage("کد معرف شما در حافظه کپی شد");
    }
  </script>
{% endblock %}

apps/users/templates/users/patient_detail_view.html
{% extends 'base.html' %}
{% load static jalali_tags %}

{% block extra_head %}
    <link href="{% static 'css/timeline.css' %}" rel="stylesheet" />
{% endblock extra_head %}


{% block page_content %}
    <div class="row">
        <div class="col-md-12">
            <div class="book-time-container">
                <div class="header">
                </div>
                <div class="body">
                    <div class="user-header">
                        <h1>{{patient.get_full_name}}</h1>
                    </div>
                    <div class="row">
                        <div class="col-md-5">
                            <div class="user-info">
                                <table>
                                    <tr>
                                        <td>شماره موبایل:</td>
                                        <td>{{patient.mobile}}</td>
                                    </tr>
                                    <tr>
                                        <td>تاریخ تولد:</td>
                                        <td>{{patient.birth_date|default:"-"}}</td>
                                    </tr>
                                    <tr>
                                        <td>شغل:</td>
                                        <td>{{patient.career|default:"-"}}</td>
                                    </tr>
                                    <tr>
                                        <td>وضعیت تاهل:</td>
                                        <td>{{patient.marriage_status|default:"-"}}</td>
                                    </tr>
                                    <tr>
                                        <td>جنسیت:</td>
                                        <td>{{patient.gender|default:"-"}}</td>
                                    </tr>
                                    <tr>
                                        <td>آدرس:</td>
                                        <td>{{patient.address|default:"-"}}</td>
                                    </tr>
                                    <tr>
                                        <td>تفلن ثابت:</td>
                                        <td>{{patient.phone_number|default:"-"}}</td>
                                    </tr>
                                    <tr>
                                        <td>بیماری‌های فعلی:</td>
                                        <td>{% for ilness in patient.current_illness.all %}
                                                <div>{{ilness}}</div>
                                            {% empty %}
                                                <div>-</div>
                                            {% endfor %}
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>داروهای مصرفی:</td>
                                        <td>{{patient.current_medicines|default:"-"}}</td>
                                    </tr>
                                    <tr>
                                        <td>سوابق درمانی:</td>
                                        <td>{{patient.treatment_history|default:"-"}}</td>
                                    </tr>
                                </table>

                                <div class="action-buttons">
                                    <a class="btn btn-default" href="{% url 'users:patient_edit' patient.id %}">
                                        <i class="fa fa-edit"></i> ویرایش پرونده
                                    </a>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-7">
                            <div class="x_content">
                                <div class="" role="tabpanel" data-example-id="togglable-tabs">
                                    <ul id="myTab1" class="nav nav-tabs bar_tabs" role="tablist">
                                        <li role="presentation" class="active">
                                            <a href="#historyTabContent" id="historyTab" role="tab" data-toggle="tab"
                                                aria-controls="history" aria-expanded="true">سابقه درمان</a>
                                        </li>
                                        <li role="presentation">
                                            <a href="#galleryTabContent" id="galleryTab" role="tab" data-toggle="tab"
                                                aria-controls="gallery" aria-expanded="true">گالری تصاویر</a>
                                        </li>
                                    </ul>
                                    <div id="MyTabContent2" class="tab-content">
                                        <div role="tabpanel" class="tab-pane fade active in" id="historyTabContent" aria-labelledby="history-tab">
                                            {% include 'users/components/reservation_history.html' with reservations=patient.reservations.all %}
                                        </div>
                                        <div role="tabpanel" class="tab-pane fade" id="galleryTabContent" aria-labelledby="gallery-tab">
                                            {% include 'users/components/image_gallery.html' with images=patient.images.all %}
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock page_content %}