apps/users/urls.py
from django.urls import include, path
from apps.users.views import (
    DashboardView, ProfileUpdateView, UserListView, UserUpdateView,
    UserCreateView, UserSetPasswordView
)


app_name = 'users'

urlpatterns = [
    path('', UserListView.as_view(), name='user_list'),
    path('new/', UserCreateView.as_view(), name='new_user'),
    path('<pk>/set-password/', UserSetPasswordView.as_view(), name='set_password'),
    path('dashboard/', DashboardView.as_view(), name='dashboard'),
    path('profile/', DashboardView.as_view(), name='profile'),
    path('profile/update/', ProfileUpdateView.as_view(), name='update_profile'),
    path('<pk>/update/', UserUpdateView.as_view(), name='update_user'),
]

holofin/urls.py
from django.contrib import admin
from django.shortcuts import redirect
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


def home(request):
    return redirect('users:dashboard')
    

urlpatterns = [
    path('', home),
    path('d/admin/', admin.site.urls),
    path('core/', include('apps.core.urls')),
    path('users/', include('apps.users.urls')),
    path('auth/', include('apps.users.auth_urls')),
    path('institution/', include('apps.institution.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/users/models.py
from time import perf_counter
from django.templatetags.static import static
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.urls import reverse
from apps.core.models import AbstractModel
from apps.institution.models import Institution
from .validators import MobileValidator, NationalCodeValidator
from .managers import CustomUserManager



class User(AbstractUser, AbstractModel):
    """Custom User model"""
    class DeactivateReasons(models.IntegerChoices):
        UNKNOWN = 0, 'نامشخص'
        BY_ADMIN = 1, 'غیر فعال توسط مدیر'
        VERIFY_MOBILE = 2, 'عدم تایید موبایل'
        VERIFY_EMAIL = 3, 'عدم تایید ایمیل'
    
    class Roles(models.IntegerChoices):
        ADMIN = 0, 'مدیر'
        USER = 1, 'کاربر'

    mobile = models.CharField('موبایل', max_length=11, unique=True,
                              help_text='موبایل باید به فرمت 09123456789 وارد شود',
                              validators=[MobileValidator()],
                              error_messages={
                                  'unique': 'این شماره موبایل از قبل در سامانه ثبت شده است',
                                },
                            )
    password = models.CharField('گذرواژه', max_length=128, null=True, blank=True)
    first_name = models.CharField(verbose_name='نام', max_length=150, blank=True)
    last_name = models.CharField(verbose_name='نام خانوادگی', max_length=150, blank=True)
    national_code = models.CharField(max_length=10, verbose_name='کد ملی',
                                     validators=[NationalCodeValidator()],
                                     null=True, blank=True, unique=True)
    deactivate_reason = models.PositiveSmallIntegerField(choices=DeactivateReasons.choices,
                                                         default=DeactivateReasons.UNKNOWN,
                                                         verbose_name='غیرفعال به دلیل')
    email = models.EmailField(unique=True, null=True, blank=True, verbose_name='ایمیل')
    address = models.TextField(verbose_name='آدرس', null=True, blank=True)
    birth_date = models.DateField(verbose_name='تاریخ تولد', null=True, blank=True)
    role = models.IntegerField(choices=Roles.choices, default=Roles.USER, verbose_name='نقش')
    phone_number = models.CharField(max_length=15, verbose_name='شماره تلفن ثابت', null=True, blank=True)
    notes = models.TextField(verbose_name='یادداشت', null=True, blank=True)
    avatar = models.ImageField(verbose_name='تصویر پروفایل', upload_to='users/avatars', null=True, blank=True)
    deposit_quantity = models.PositiveIntegerField(verbose_name='تعداد سهم', default=1)
    institution = models.ForeignKey(Institution, on_delete=models.PROTECT, null=True, related_name='users')
    objects = CustomUserManager()

    REQUIRED_FIELDS = ["mobile", ]

    class Meta:
        verbose_name = 'کاربر'
        verbose_name_plural = 'کاربر'
        ordering = ('-id',)

    def __str__(self):
        role = self.get_role_display()
        return f'{self.display_name} ({role})'

    def get_absolute_url(self):
        return reverse('users:user_details', kwargs={'pk': self.pk})

    def save(self, *args, **kwargs):
        if self.email == '':
            self.email = None
        if self.role == self.Roles.ADMIN:
            self.is_staff = True
            self.is_superuser = True
        super().save(*args, **kwargs)

    @property
    def display_name(self) -> str:
        return (
            self.first_name + ' ' + self.last_name
            if self.first_name and self.last_name
            else self.mobile
        )

    @property
    def avatar_url(self) -> str:
        if self.avatar:
            return self.avatar.url
        f = static('account/profile.png')
        return f

    def deactivate(self, reason: DeactivateReasons):
        """Deactivate user by reason

        DO NOT explicitly set users is_active field without saving the reason why it is deactivated
        """
        self.deactivate_reason = reason
        self.is_active = False
        self.save()

    def activate(self):
        """Activate user

        Will change user's deactivate reason to UNKNOWN
        """
        self.deactivate_reason = self.DeactivateReasons.UNKNOWN
        self.is_active = True
        self.save()

    @property
    def is_admin(self):
        return self.role == self.Roles.ADMIN

    @property
    def is_simple_user(self):
        return self.role == self.Roles.USER

apps/users/forms.py
from secrets import choice
from django import forms
from django_filters import FilterSet
from django.contrib.auth import get_user_model
from apps.core import utils
User = get_user_model()


class UserForm(forms.ModelForm):
    password_confirm = forms.CharField(
        label='تکرار رمز عبور',
        widget=forms.PasswordInput(attrs={'class': 'form-control'}),
    )
    password= forms.CharField(
        label='رمز عبور',
        widget=forms.PasswordInput(attrs={'class': 'form-control'}),
    )

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'mobile', 'role', 'avatar', 'password', 'password_confirm']

    def clean_mobile(self):
        mobile = self.cleaned_data['mobile']
        mobile = utils.persian_digits_to_english(mobile)
        return mobile

    def clean_password(self):
        password = self.cleaned_data.get('password')
        if len(password) < 8:
            raise forms.ValidationError('رمز عبور باید حداقل 8 کاراکتر باشد')
        if password.isdigit():
            raise forms.ValidationError('رمز عبور نمیتواند تنها شامل عدد باشد')
        return password

    def clean_password_confirm(self):
        password = self.cleaned_data.get('password')
        password_confirm = self.cleaned_data.get('password_confirm')
        if not password:
            return password_confirm
        if password != password_confirm:
            raise forms.ValidationError('رمز عبور و تکرار آن باید یکسان باشد')
        return password_confirm

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['first_name'].required = True
        self.fields['last_name'].required = True

        
class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'mobile', 'role', 'avatar']

    def clean_mobile(self):
        mobile = self.cleaned_data['mobile']
        mobile = utils.persian_digits_to_english(mobile)
        return mobile

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['role'].widget.choices = UserForm.remove_patient_from_roles(User.Roles.choices)
        self.fields['first_name'].required = True
        self.fields['last_name'].required = True
 
        
class UserSetPasswordForm(forms.ModelForm):
    password_confirm = forms.CharField(
        label='تکرار رمز عبور',
        widget=forms.PasswordInput(attrs={'class': 'form-control'}),
    )
    password= forms.CharField(
        label='رمز عبور',
        widget=forms.PasswordInput(attrs={'class': 'form-control'}),
    )


    class Meta:
        model = User
        fields = ['password', 'password_confirm']

    def clean_password(self):
        password = self.cleaned_data.get('password')
        if len(password) < 8:
            raise forms.ValidationError('رمز عبور باید حداقل 8 کاراکتر باشد')
        if password.isdigit():
            raise forms.ValidationError('رمز عبور نمیتواند تنها شامل عدد باشد')
        return password

    def clean_password_confirm(self):
        password = self.cleaned_data.get('password')
        password_confirm = self.cleaned_data.get('password_confirm')
        if not password:
            return password_confirm
        if password != password_confirm:
            raise forms.ValidationError('رمز عبور و تکرار آن باید یکسان باشد')
        return password_confirm


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'national_code',
                  'email', 'address', 'avatar', 'deposit_quantity')
         

apps/users/views.py
from django.urls import reverse_lazy
from django.shortcuts import get_object_or_404, redirect, render
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils.translation import gettext_lazy as _
from django.views.generic import View, ListView, CreateView, UpdateView, TemplateView, FormView
from jalali_date import date2jalali, datetime2jalali
from apps.core.permissions import PermissionRequireMixin, Permissions
from apps.core.base import BaseContextMixin, GenericFormView, GenericModelFormView
from apps.core.mixins import CustomFormTemplateMixin, CustomListTemplateMixin
from .forms import UserForm, UserProfileForm, UserUpdateForm, UserSetPasswordForm
User = get_user_model()


class DashboardView(LoginRequiredMixin, BaseContextMixin, View):
    def get(self, request, *args, **kwargs):
        context = self.get_context_data(**kwargs)
        return render(request, 'users/dashboard.html', context)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


class ProfileUpdateView(LoginRequiredMixin, CustomFormTemplateMixin, UpdateView):
    model = User
    form_class = UserProfileForm
    success_url = reverse_lazy('users:dashboard')
    success_message = 'اطلاعات شما با موفقیت بروزرسانی شد.'
    page_title = 'ویرایش پروفایل'

    def get_page_subtitle(self):
        user = self.request.user
        return user.get_full_name()

    def get_object(self, queryset=None):
        return self.request.user

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['extra_scripts'] = ['users/scripts/career_dropdown.js']
        return context

        
class UserListView(CustomListTemplateMixin, PermissionRequireMixin, ListView):
    permissions =  [User.Roles.ADMIN, ]
    page_title = 'لیست کاربران'
    context_object_name = 'users'
    paginate_by = 100
    ordering = '-created_at'
    fields = ['username', 'first_name', 'last_name', 'role',]
    header_buttons = [{'title': 'افزودن کاربر', 'url': reverse_lazy('users:new_user')}]
    action_buttons = [
        {'title': 'ویرایش', 'url_name': 'users:update_user', 'arg_field': 'id',
         'fa-icon': 'fa-edit', 'class': '', 'class_form_field': 'id'},
        {'title': 'تغییر رمز', 'url_name': 'users:set_password', 'arg_field': 'id',
         'fa-icon': 'fa-edit', 'class': 'btn-warning', 'class_form_field': 'id'},
    ]

    def get_queryset(self):
        institution = self.request.user.institution
        return User.objects.filter(institution=institution)

    def get_role(self, obj):
        return obj.get_role_display()

    def get_created_at(self, obj):
        return datetime2jalali(obj.created_at).strftime('%Y/%m/%d %H:%M:%S')

    def get_last_login(self, obj):
        last_login = obj.last_login
        if last_login:
            return datetime2jalali(last_login).strftime('%Y/%m/%d %H:%M:%S')
        return '-'


class UserCreateView(CustomFormTemplateMixin, PermissionRequireMixin, CreateView):
    permissions = [User.Roles.ADMIN]
    model = User
    form_class = UserForm
    page_title = 'افزودن کاربر جدید'
    success_url = reverse_lazy('users:user_list')
    cancel_url = reverse_lazy('users:user_list')
    success_message = ' کاربر جدید با موفقیت ثبت شد.'

    def form_valid(self, form):
        user = form.save(commit=False)
        password = user.password
        user.username = user.mobile
        user.institution = self.request.user.institution
        user.set_password(password)
        user.save()
        return super().form_valid(form)



class UserUpdateView(UserCreateView, UpdateView):
    page_title = 'ویرایش کاربر'
    success_message = 'کاربر با موفقیت ویرایش شد.'
    form_class = UserUpdateForm


class UserSetPasswordView(CustomFormTemplateMixin, PermissionRequireMixin, FormView):
    permissions = [User.Roles.ADMIN]
    model = User
    form_class = UserSetPasswordForm
    success_url = reverse_lazy('users:user_list')
    success_message = 'رمز عبور با موفقیت بروزرسانی شد.'
    page_title = 'تغییر رمز عبور'
    
    def get_page_subtitle(self):
        user = self.get_object()
        return user.get_full_name()

    def get_object(self, queryset=None):
        pk = self.kwargs.get('pk')
        return get_object_or_404(User, pk=pk)
    
    def form_valid(self, form):
        user = self.get_object()
        user.set_password(form.cleaned_data['password'])
        user.save()
        return super().form_valid(form)


class UserDetailView(PermissionRequireMixin ,TemplateView):
    permissions = [User.Roles.ADMIN]
    template_name = 'users/user_detail_view.html'
    context_object_name = 'user'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = get_object_or_404(User, id=kwargs['pk'])
        context["user"] = user
        return context

apps/users/templates/gentellela/auth_base.html
{% load static i18n %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  <!-- Meta, title, CSS, favicons, etc. -->
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <title>{{ site_name }}</title>


  <!-- Bootstrap -->
  <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">
  <link href="{% static "css/bootstrap-rtl.min.css" %}" rel="stylesheet">
  <!-- Font Awesome -->
  <link href="{% static "css/font-awesome.min.css" %}" rel="stylesheet">
  <!-- Custom Theme Style -->
  <link href="{% static "css/custom.min.css" %}" rel="stylesheet">


</head>

<body class="auth">
  <div class="wrapper">
      {% block content %}
      {% endblock %}
  </div>
</body>

</html>

apps/users/templates/gentellela/email_sent.html
{% extends 'gentellela/auth_base.html' %}
{% load static i18n %}

{% block content %}
  <div class="animate form login_form">
    <section class="login_content">
      <div style="position: relative; margin:20px 0px;">

        <h1>{% trans 'توجه!' %}</h1>
        <p>{% trans 'درخواست شما با موفقیت ثبت شد' %}</p>
        <p>{% trans 'در صورتی که با این آدرس ایمیل در سایت ما ثبت نام کرده باشید، ایمیلی حاوی لینک تغییر رمز برای شما ارسال خواهد شد' %}</p>
        <div class="login_footer">
          {% include 'gentellela/page_footer.html' %}
        </div>
      </div>
    </section>
  </div>
{% endblock content %}

apps/users/templates/gentellela/forgot_password.html
{% extends 'gentellela/auth_base.html' %}
{% load static i18n %}

{% block content %}
    <div class="animate form login_form">
      <section class="login_content">
        <form method="POST" action="{% url 'account_forgot_password' %}">
          {%csrf_token%}
          <h1>{% trans 'بازیابی رمز ورود' %}</h1>
          {% for hidden_field in form.hidden_fields %}
          {{ hidden_field }}
          {% endfor %}

          {% if form.non_field_errors %}
          <div class="alert alert-danger" role="alert">
            {% for error in form.non_field_errors %}
            {{ error }}
            {% endfor %}
          </div>
          {% endif %}

          {% for field in form.visible_fields %}
          <div>
            {% if form.is_bound %}
            {{ field }}
            {% if field.errors %}
            <div class="alert alert-danger alert-dismissible fade in">
              <ul>
                {% for error in field.errors %}
                <li>
                  {{ error }}
                </li>
                {% endfor %}
              </ul>
            </div>
            {% endif %}
            {% else %}
            {{ field }}
            {% endif %}
            {% if field.help_text %}
            <small class="form-text text-muted">{{ field.help_text }}</small>
            {% endif %}
          </div>
          {% endfor %}

          <div>
            <input type="submit" class="btn btn-default submit" value="{% trans 'ارسال' %}" />
          </div>

          <div class="clearfix"></div>

          <div class="separator">
            <a href="{% url 'account_login' %}" class="sub-link">{% trans 'ورود به سایت' %}</a>
          </div>

          <div class="login_footer">
            {% include 'gentellela/page_footer.html' %}
          </div>

        </form>
      </section>
    </div>

{% endblock content %}

apps/users/templates/gentellela/page_footer.html
<p>Made with
    <svg class="heart" viewBox="0 0 32 29.6">
        <path d="M23.6,0c-3.4,0-6.3,2.7-7.6,5.6C14.7,2.7,11.8,0,8.4,0C3.8,0,0,3.8,0,8.4c0,9.4,9.5,11.9,16,21.2
        c6.1-9.3,16-12.1,16-21.2C32,3.8,28.2,0,23.6,0z" />
    </svg>
    by <a href="http://mohsen-hassani.ir" style="color: lightcyan; font-size: 13px; text-decoration: underline;">Mohsen Hassani</a>
</p>

apps/users/templates/gentellela/profile_form.html
{% extends 'base.html' %}
{% load static jalali_tags i18n %}
{% block title %} {{block.super}}
{{ page_title }}
{% endblock title %}

{% block extra_head %}
{{extra_head|safe}}
<style>
    .birth_date {
        border-radius: 5px;
    }
    #id_email {
        background-color: lightgray;
    }
</style>
{% endblock extra_head %}



{%block page_content%}
<div class="x_panel">
<div class="x_title">
            <h2>
                {% trans 'ویرایش پروفایل' %}
                <small>{{user.username}}</small>
            </h2>
            <ul class="nav navbar-right panel_toolbox">
                <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                </li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" kerman_case="button"
                        aria-expanded="false"><i class="fa fa-wrench"></i></a>
                </li>
                <li><a class="close-link"><i class="fa fa-close"></i></a>
                </li>
            </ul>
            <div class="clearfix"></div>
        </div>

    <div class="x_content">
        <form id="updateProfile" data-parsley-validate class="form-horizontal form-label-left" action=""
              enctype="multipart/form-data" method="POST">

            {% csrf_token %}

            {% if form.non_field_errors %}
            <div class="alert alert-danger" role="alert">
                {% for error in form.non_field_errors %}
                    {{ error }}
                {% endfor %}
            </div>
            {% endif %}

            <!-- Email -->
            <div class="form-group">
                <label class="control-label col-md-3 col-sm-2 col-xs-12" for="{{user_form.email.id_for_label}}">
                    {{ user_form.email.label_tag }}
                    {% if user_form.email.field.required %}
                        <span class="required">*</span>
                    {%endif %}
                </label>
                <div class="col-md-6 col-sm-10 col-xs-12">
                {{ user_form.email }}
                <small class="form-text text-muted">{{ user_form.email.help_text }}</small>
                {% if user_form.email.errors %}
                    {% for error in user_form.email.errors %}
                    <div class="invalid-feedback">
                        {{ error }}
                    </div>
                    {% endfor %}
                {% endif %}
                </div>
            </div>


            <!-- First name -->
            <div class="form-group">
                <label class="control-label col-md-3 col-sm-2 col-xs-12" for="{{user_form.first_name.id_for_label}}">
                    {{ user_form.first_name.label_tag }}
                    {% if user_form.first_name.field.required %}
                        <span class="required">*</span>
                    {%endif %}
                </label>
                <div class="col-md-6 col-sm-10 col-xs-12">
                {{ user_form.first_name }}
                <small class="form-text text-muted">{{ user_form.first_name.help_text }}</small>
                {% if user_form.first_name.errors %}
                    {% for error in user_form.first_name.errors %}
                    <div class="invalid-feedback">
                        {{ error }}
                    </div>
                    {% endfor %}
                {% endif %}
                </div>
            </div>



            <!-- Last name -->
            <div class="form-group">
                <label class="control-label col-md-3 col-sm-2 col-xs-12" for="{{user_form.last_name.id_for_label}}">
                    {{ user_form.last_name.label_tag }}
                    {% if user_form.last_name.field.required %}
                        <span class="required">*</span>
                    {%endif %}
                </label>
                <div class="col-md-6 col-sm-10 col-xs-12">
                {{ user_form.last_name }}
                <small class="form-text text-muted">{{ user_form.last_name.help_text }}</small>
                {% if user_form.last_name.errors %}
                    {% for error in user_form.last_name.errors %}
                    <div class="invalid-feedback">
                        {{ error }}
                    </div>
                    {% endfor %}
                {% endif %}
                </div>
            </div>


            <!-- Phone number -->
            <div class="form-group">
                <label class="control-label col-md-3 col-sm-2 col-xs-12" for="{{profile_form.phone_number.id_for_label}}">
                    {{ profile_form.phone_number.label_tag }}
                    {% if profile_form.phone_number.field.required %}
                        <span class="required">*</span>
                    {%endif %}
                </label>
                <div class="col-md-6 col-sm-10 col-xs-12">
                {{ profile_form.phone_number }}
                <small class="form-text text-muted">{{ profile_form.phone_number.help_text }}</small>
                {% if profile_form.phone_number.errors %}
                    {% for error in profile_form.phone_number.errors %}
                    <div class="invalid-feedback">
                        {{ error }}
                    </div>
                    {% endfor %}
                {% endif %}
                </div>
            </div>


            <!-- Avatar -->
            <div class="form-group">
                <label class="control-label col-md-3 col-sm-2 col-xs-12" for="{{profile_form.avatar.id_for_label}}">
                    {{ profile_form.avatar.label_tag }}
                    {% if profile_form.avatar.field.required %}
                        <span class="required">*</span>
                    {%endif %}
                </label>
                <div class="col-md-6 col-sm-10 col-xs-12">
                {{ profile_form.avatar }}
                <small class="form-text text-muted">{{ profile_form.avatar.help_text }}</small>
                {% if profile_form.avatar.errors %}
                    {% for error in profile_form.avatar.errors %}
                    <div class="invalid-feedback">
                        {{ error }}
                    </div>
                    {% endfor %}
                {% endif %}
                </div>
            </div>


            <!-- Birth date -->
            {{ profile_form.birth_date.as_hidden }}
            <div class="form-group">
                <label class="control-label col-md-3 col-sm-2 col-xs-12" for="{{profile_form.birth_date.id_for_label}}">
                    {{ profile_form.birth_date.label_tag }}
                    {% if profile_form.birth_date.field.required %}
                        <span class="required">*</span>
                    {%endif %}
                </label>
                <div class="col-md-6 col-sm-10 col-xs-12">
                    <div class="row">
                        <div class="col-md-4">
                            <select class="form-control birth_date" id="year">
                                <option value="">سال</option>
                                {% for year in years %}
                                    <option value="{{ year }}">{{ year }}</option>
                                {% endfor %}
                            </select>
                        </div>
                        <div class="col-md-4">
                            <select class="form-control birth_date" id="month">
                                <option value="">ماه</option>
                                <option value="1">فروردین</option>
                                <option value="2">اردیبهشت</option>
                                <option value="3">خرداد</option>
                                <option value="4">تیر</option>
                                <option value="5">مرداد</option>
                                <option value="6">شهریور</option>
                                <option value="7">مهر</option>
                                <option value="8">آبان</option>
                                <option value="9">آذر</option>
                                <option value="10">دی</option>
                                <option value="11">بهمن</option>
                                <option value="12">اسفند</option>
                            </select>
                        </div>
                        <div class="col-md-4">
                            <select class="form-control birth_date" id="day">
                                <option value="">روز</option>
                                <option value="1">1</option>
                                <option value="2">2</option>
                                <option value="3">3</option>
                                <option value="4">4</option>
                                <option value="5">5</option>
                                <option value="6">6</option>
                                <option value="7">7</option>
                                <option value="8">8</option>
                                <option value="9">9</option>
                                <option value="10">10</option>
                                <option value="11">11</option>
                                <option value="12">12</option>
                                <option value="13">13</option>
                                <option value="14">14</option>
                                <option value="15">15</option>
                                <option value="16">16</option>
                                <option value="17">17</option>
                                <option value="18">18</option>
                                <option value="19">19</option>
                                <option value="20">20</option>
                                <option value="21">21</option>
                                <option value="22">22</option>
                                <option value="23">23</option>
                                <option value="24">24</option>
                                <option value="25">25</option>
                                <option value="26">26</option>
                                <option value="27">27</option>
                                <option value="28">28</option>
                                <option value="29">29</option>
                                <option value="30">30</option>
                                <option value="31">31</option>
                            </select>
                        </div>
                    </div>
               <small class="form-text text-muted">{{ profile_form.birth_date.help_text }}</small>
                {% if profile_form.birth_date.errors %}
                    {% for error in profile_form.birth_date.errors %}
                    <div class="invalid-feedback">
                        {{ error }}
                    </div>
                    {% endfor %}
                {% endif %}
                </div>
            </div>





            <div class="ln_solid"></div>
            <div class="form-group">
                <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                    
                    {% if submit_buttons %}
                        {% for submit in submit_buttons %}
                            <button type="submit" name="{{submit.name}}" class="btn {{submit.class}}">
                                {{submit.title}}
                            </button>
                        {% endfor %}
                    {% else %}
                        <button type="submit" class="btn btn-success">
                            {% if form_submit_btn_text %}
                            {{form_submit_btn_text}}
                            {% else %}
                            {% trans 'ارسال' %}
                            {% endif %}
                        </button>
                    {% endif %}

                    {% if form_cancel_url_name %}
                    <a {% if form_cancel_url_arg1 %} href="{% url form_cancel_url_name form_cancel_url_arg1 %}" {% else %}
                        href="{% url form_cancel_url_name %}" {% endif %} class="btn btn-default">
                        {% if form_cancel_btn_text %}
                        {{form_cancel_btn_text}}
                        {% else %}
                        {% trans 'انصراف' %}
                        {% endif %}
                    </a>
                    {% endif %}
                </div>
            </div>

        </form>
    </div>
</div>

<script>
    $(document).ready(function(){
        let user_birth_date = '{{user.profile.birth_date|to_jalali:"%Y-%m-%d"}}';
        if(user_birth_date.length > 8){
            return;
        }
        const [year, month, day] = user_birth_date.split('-');
        $("#year").val(parseInt(year));
        $("#month").val(parseInt(month));
        $("#day").val(parseInt(day));

        $('.birth_date').change(function(){
            let year = $('#year').val();
            let month = $('#month').val();
            let day = $('#day').val();

            if(year && month && day){
                $('#id_birth_date').val(year + '-' + month + '-' + day);
            }

        });
    });
</script>
{%endblock page_content%}